### ISSUE TITLE
Support custom data-reader tags

### ISSUE THREAD

**Issue by clyfe** [gfredericks/vcr-clj#11]
When doing generic io record/playback custom tags may be used when serializing, and deserialization might fail. Please allow option to provide custom tags to the edn reader.

**Comment by gfredericks** [comment]
This would just be adding something to the API that would end up customizing [this line](https://github.com/gfredericks/vcr-clj/blob/07fd6af31fb638fc21037d67e771c2346691c79c/src/vcr_clj/cassettes.clj#L28), is that correct?

**Comment by clyfe** [comment]
Yes, that's correct.

**Comment by gfredericks** [comment]
If I changed it so that `clojure.core/*data-readers*` was used, would that be sufficient?

**Comment by gfredericks** [comment]
I just created a branch at #20 that does this.

**Comment by gfredericks** [comment]
This feature was added by #26.
