### ISSUE TITLE
 Playing back cartridges with https data fails

### ISSUE THREAD

**Issue by paulspencerwilliams** [gfredericks/vcr-clj#2]
I've successfully used cartridge to record and playback plain http traffic. However, when I try to record and playback encrypted https traffic, (json in my case), data from the resultant playback is invalid - I believe encrypted. Certainly, the contents of the cassette file is encrypted.

**Comment by gfredericks** [comment]
Having somebody else run into this compelled me to come up with a cleaner solution than the one I put in the alpha release, so this should now be fixed in the latest release: `0.4.1`.
