### ISSUE TITLE
clj-http cassettes change response body

### ISSUE THREAD

**Issue by bripkens** [gfredericks/vcr-clj#4]
The usage of `vcr-clj.clj-http/with-cassette` changes the response body to gibberish when a cassette exist. The initial request, i.e. when no cassette exists, works fine.

Example:

Source:
```clojure
(println (:body (client/post "http://example.com" {})))

; when no cassette exists:
; {"id": "foobar"...}

; when a cassette exists:
; }P�N�@�s�R����1(QK Ęf�...
```

Test:
```clojure
(deftest sign-in
  (with-cassette
    :sign-in
    (auth/sign-in (:email test-user)
                  (:password test-user))))
```

I should mention that the response is gzipped, but according to your tests this should be supported?

**Comment by bripkens** [comment]
Dependency versions:

```
[com.gfredericks/vcr-clj "0.4.0"]
[clj-http "1.0.1"]
```

**Comment by gfredericks** [comment]
Could you try with version `0.3.4-alpha1` and see if that fixes the problem?

I should have just released those changes to prevent other people from having this issue but I was so frustrated with having to extend `print-method` that I hadn't yet.

That alpha release came out of issue #2.

**Comment by bripkens** [comment]
Thanks, version `0.3.4-alpha1` works. Do you need more information to fix the issue in version `0.4.0`?

**Comment by gfredericks** [comment]
Nope, should just be a merge. I'll do it now.

**Comment by gfredericks** [comment]
and of course it's a hairy merge and my tests are failing now but on the bright side I thought of a cleaner way of fixing the original problem.

**Comment by bripkens** [comment]
Alright, thanks for your effort and help!

**Comment by gfredericks** [comment]
Phew okay I think I bent everything back into shape. Try out the new release, `0.4.1`, and let me know if you have any problems.

**Comment by bripkens** [comment]
Works nicely, well done!
