### ISSUE TITLE
still have `update` warining issue on 0.4.3

### ISSUE THREAD

**Issue by wilkerlucio** [gfredericks/vcr-clj#7]
Hi,

I see that the changes for the version 0.4.3 are to avoid the `update` warning issue, but here this issue still persists. Maybe the deployed code is not updated?

Thanks.

**Comment by gfredericks** [comment]
Indeed you're right! `0.4.4` should be better. The reason for why [this commit](https://github.com/gfredericks/vcr-clj/commit/1931e59966df54cd6594d32e8c5c1a9596e9e16b) didn't do what it was trying to do is left as an exercise for the reader.

**Comment by wilkerlucio** [comment]
cool, thanks :)
